name = "jitshub"
compatibility_date = "2024-09-24"
compatibility_flags = [ "nodejs_compat" ]

[vars]
SECRET_KEY = "hehehehehe"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTBhODc2NzEtNzJlYy00NDAyLWFhZjEtMWU4MjYwMjBmODEzIiwidGVuYW50X2lkIjoiNWVkYzI4NzM5ZTdiNjlkMTRkNjJmZGVkZWYwYTNkMTM4YTkyMzk0N2NhMWQ0NjYwZTI0YmM5OGY5OTgxY2VkOSIsImludGVybmFsX3NlY3JldCI6ImNiZDBkOTFhLTdiMjItNDRhNy1iZTEyLTM0OGI5ZjZjZjYwMCJ9.GjNePnh1to1hAZQZvpsEzgUxIl1KEn9bfWIjh0tR938"

DIRECT_URL="postgresql://JitsHub_owner:jBlm0nTFPpE1@ep-polished-term-a1k7uvi0.ap-southeast-1.aws.neon.tech/JitsHub?sslmode=require"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"